# Generated by Django 5.1.4 on 2025-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_size', models.JSONField()),
                ('location', models.JSONField()),
                ('rental_type', models.CharField(choices=[('SINGLE ROOM', 'SR'), ('BEDSITTER', 'BS'), ('ONE BEDROOM', 'BR1'), ('TWO BEDROOM', 'BR2'), ('THREE BEDROOM', 'BR3'), ('FOUR BEDROOM', 'BR4'), ('OFFICE SPACE', 'OFFICE'), ('BUSINESS STALL', 'STALL')], default='BEDSITTER', max_length=20)),
                ('distance_from_tarmac', models.CharField(max_length=100)),
                ('distance_from_cbd', models.CharField(max_length=200)),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.BooleanField(default=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vacant', models.BooleanField(default=True)),
                ('area', models.CharField(max_length=250)),
                ('bathrooms', models.IntegerField()),
                ('amenities', models.TextField()),
                ('multi_storey', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rental_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
