# Generated by Django 5.1.4 on 2025-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='building_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
